admin:
  categories:
    per_page: 5
  users:
    per_page: 5
  posts:
    per_page: 5
    normal_post: 0
    audio_post: 1
  advertisments:
    per_page: 5
time_format:
  normal: "%d-%m-%Y %H:%M"

per_page: 10

