admin:
  categories:
    per_page: 5
  users:
    per_page: 5
  posts:
    per_page: 5
    normal_post: 0
    audio_post: 1
    accept: "Accept"
    reject: "Reject"
  advertisments:
    per_page: 5
  confessions:
    per_page: 5
    length_read_more: 30
  format_date_time: "%m/%d/%Y at %I:%M%p"
time_format:
  normal: "%H:%M %d-%m-%Y"
per_page: 10
